name: Main Workflow
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version:'18'
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Completed lint
        run: echo "Linting completed successfully!"
  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version:'18'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run test
      - name: Completed tests 
        run: echo "Testing completed successfully!"
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version:'18'
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Completed build 
        run: echo "Build completed successfully!"